version: '3'
services:
  watchdog:
    build: .
    image: ghcr.io/groveld/watchdog
    container_name: watchdog
    restart: always
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "5052:5052"

networks:
  backend:
    driver: bridge
